### PR TITLE
Rework Dockerfiles to allow build with Poetry

### PR DESCRIPTION
**Pull request by Sannholm**
- `requirements.txt` files are no longer needed
- Backend no longer depends on `docker` image or the docker CLI command (Docker API is used instead)
- A multi-stage build is used so a minimal set of files and tools are left in the final image

Frontend-backend communication (HTTP API) #51 depends on these changes for the build to succeed.

Remaining issues:
- Database connection config in frontend should be moved into environment variables so it can be easily configured in docker-compose. The default can then be changed from `database` to `localhost` to allow the frontend database tests to work.
- Windows-style line ending in `genkeys` and `custom-cont-init.d\init.sh` break the build on Windows.
- Pytest could be run in containers to make sure the test environment is consistent. For example, the database container could additionally be started automatically along with running the tests to allow the frontend tests to pass by default.

### CODE REVIEW

**Review by osksvan — CHANGES_REQUESTED** [review]
Build is failing for me due to missing /opt/protocols, seems to be the same for both for the frontend and backend, as well as the one in /dev. I cannot see /opt/protocols in this branch, did you forget it?
image
Database is working fine.

Otherwise it is looking good.

**Comment by Sannholm** [comment]
> Build is failing for me due to missing /opt/protocols, seems to be the same for both for the frontend and backend, as well as the one in /dev. I cannot see /opt/protocols in this branch, did you forget it?
> image
> Database is working fine.
> 
> Otherwise it is looking good.

Oh yeah, I tried to separate out the stuff that was specific to the HTTP API from this PR but forgot that.

**Comment by Sannholm** [comment]
> Build is failing for me due to missing /opt/protocols, seems to be the same for both for the frontend and backend, as well as the one in /dev. I cannot see /opt/protocols in this branch, did you forget it?
> image
> Database is working fine.
> 
> Otherwise it is looking good.

This should be fixed now!

**Review by osksvan — APPROVED** [review]

**Review by Bonzo1 — APPROVED** [review]
Everythings seems to be working. Good job!

**Review by ALX99 — APPROVED** [review]
Very nice

**Pull request merged**
